# Site settings
title: Thinking out loud
email: ohpreis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  TOL is my small place that I use as a pulpit. Nothing much, just some short
  posts to vent about this and that. Do think out loud if you will.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
